interface Option {
  label: string;
  value: string;
  category?: boolean;
}

export const mantineOptions: Option[] = [
  // mantine colors
  { label: 'dark-0', value: '#C1C2C5' },
  { label: 'dark-1', value: '#A6A7AB' },
  { label: 'dark-2', value: '#909296' },
  { label: 'dark-3', value: '#5C5F66' },
  { label: 'dark-4', value: '#373A40' },
  { label: 'dark-5', value: '#2C2E33' },
  { label: 'dark-6', value: '#25262B' },
  { label: 'dark-7', value: '#1A1B1E' },
  { label: 'dark-8', value: '#141517' },
  { label: 'dark-9', value: '#101113' },
  { label: 'gray-0', value: '#F8F9FA' },
  { label: 'gray-1', value: '#F1F3F5' },
  { label: 'gray-2', value: '#E9ECEF' },
  { label: 'gray-3', value: '#DEE2E6' },
  { label: 'gray-4', value: '#CED4DA' },
  { label: 'gray-5', value: '#ADB5BD' },
  { label: 'gray-6', value: '#868E96' },
  { label: 'gray-7', value: '#495057' },
  { label: 'gray-8', value: '#343A40' },
  { label: 'gray-9', value: '#212529' },
  { label: 'red-0', value: '#FFF5F5' },
  { label: 'red-1', value: '#FFE3E3' },
  { label: 'red-2', value: '#FFC9C9' },
  { label: 'red-3', value: '#FFA8A8' },
  { label: 'red-4', value: '#FF8787' },
  { label: 'red-5', value: '#FF6B6B' },
  { label: 'red-6', value: '#FF5252' },
  { label: 'red-7', value: '#F03E3E' },
  { label: 'red-8', value: '#E03131' },
  { label: 'red-9', value: '#C92A2A' },
  { label: 'pink-0', value: '#FFF0F6' },
  { label: 'pink-1', value: '#FFDEEB' },
  { label: 'pink-2', value: '#FCC2D7' },
  { label: 'pink-3', value: '#FAA2C1' },
  { label: 'pink-4', value: '#F783AC' },
  { label: 'pink-5', value: '#F06595' },
  { label: 'pink-6', value: '#E64980' },
  { label: 'pink-7', value: '#D6336C' },
  { label: 'pink-8', value: '#C2255C' },
  { label: 'pink-9', value: '#A61E4D' },
  { label: 'grape-0', value: '#F8F0FC'},
  { label: 'grape-1', value: '#F3D9FA' },
  { label: 'grape-2', value: '#EEBEFA' },
  { label: 'grape-3', value: '#E599F7' },
  { label: 'grape-4', value: '#DA77F2' },
  { label: 'grape-5', value: '#CC5DE8' },
  { label: 'grape-6', value: '#BE4BDB' },
  { label: 'grape-7', value: '#AE3EC9' },
  { label: 'grape-8', value: '#9C36B5' },
  { label: 'grape-9', value: '#862E9C' },
  { label: 'violet-0', value: '#F3F0FF' },
  { label: 'violet-1', value: '#E5DBFF' },
  { label: 'violet-2', value: '#D0BFFF'},
  { label: 'violet-3', value: '#B197FC' },
  { label: 'violet-4', value: '#9775FA' },
  { label: 'violet-5', value: '#845EF7' },
  { label: 'violet-6', value: '#7950F2' },
  { label: 'violet-7', value: '#7048E8' },
  { label: 'violet-8', value: '#6741D9' },
  { label: 'violet-9', value: '#5F3DC4' },
  { label: 'indigo-0', value: '#EDF2FF' },
  { label: 'indigo-1', value: '#DBE4FF' },
  { label: 'indigo-2', value: '#BAC8FF'},
  { label: 'indigo-3', value: '#91A7FF' },
  { label: 'indigo-4', value: '#748FFC' },
  { label: 'indigo-5', value: '#5C7CFA' },
  { label: 'indigo-6', value: '#4C6EF5' },
  { label: 'indigo-7', value: '#4263EB' },
  { label: 'indigo-8', value: '#3B5BDB' },
  { label: 'indigo-9', value: '#364FC7' },
  { label: 'blue-0', value: '#E7F5FF' },
  { label: 'blue-1', value: '#D0EBFF' },
  { label: 'blue-2', value: '#A5D8FF' },
  { label: 'blue-3', value: '#74C0FC' },
  { label: 'blue-4', value: '#4DABF7' },
  { label: 'blue-5', value: '#339AF0' },
  { label: 'blue-6', value: '#228BE6' },
  { label: 'blue-7', value: '#1C7ED6' },
  { label: 'blue-8', value: '#1971C2' },
  { label: 'blue-9', value: '#1864AB' },
  { label: 'cyan-0', value: '#E3FAFC' },
  { label: 'cyan-1', value: '#C5F6FA' },
  { label: 'cyan-2', value: '#99E9F2' },
  { label: 'cyan-3', value: '#66D9E8' },
  { label: 'cyan-4', value: '#3BC9DB' },
  { label: 'cyan-5', value: '#22B8CF' },
  { label: 'cyan-6', value: '#15AABF' },
  { label: 'cyan-7', value: '#1098AD' },
  { label: 'cyan-8', value: '#0C8599' },
  { label: 'cyan-9', value: '#0B7285' },
  { label: 'teal-0', value: '#E6FCF5' },
  { label: 'teal-1', value: '#C3FAE8' },
  { label: 'teal-2', value: '#96F2D7' },
  { label: 'teal-3', value: '#63E6BE' },
  { label: 'teal-4', value: '#38D9A9' },
  { label: 'teal-5', value: '#20C997' },
  { label: 'teal-6', value: '#12B886' },
  { label: 'teal-7', value: '#0CA678' },
  { label: 'teal-8', value: '#099268' },
  { label: 'teal-9', value: '#087F5B' },
  { label: 'green-0', value: '#EBFBEE' },
  { label: 'green-1', value: '#D3F9D8' },
  { label: 'green-2', value: '#B2F2BB' },
  { label: 'green-3', value: '#8CE99A' },
  { label: 'green-4', value: '#69DB7C' },
  { label: 'green-5', value: '#51CF66' },
  { label: 'green-6', value: '#40C057' },
  { label: 'green-7', value: '#37B24D' },
  { label: 'green-8', value: '#2F9E44' },
  { label: 'green-9', value: '#2B8A3E' },
  { label: 'lime-0', value: '#F4FCE3' },
  { label: 'lime-1', value: '#E9FAC8' },
  { label: 'lime-2', value: '#D8F5A2' },
  { label: 'lime-3', value: '#C0EB75' },
  { label: 'lime-4', value: '#A9E34B' },
  { label: 'lime-5', value: '#94D82D' },
  { label: 'lime-6', value: '#82C91E' },
  { label: 'lime-7', value: '#74B816' },
  { label: 'lime-8', value: '#66A80F' },
  { label: 'lime-9', value: '#5C940D' },
  { label: 'yellow-0', value: '#FFF9DB' },
  { label: 'yellow-1', value: '#FFF3BF' },
  { label: 'yellow-2', value: '#FFEC99' },
  { label: 'yellow-3', value: '#FFE066' },
  { label: 'yellow-4', value: '#FFD43B' },
  { label: 'yellow-5', value: '#FCC419' },
  { label: 'yellow-6', value: '#FAB005' },
  { label: 'yellow-7', value: '#F59F00' },
  { label: 'yellow-8', value: '#F08C00' },
  { label: 'yellow-9', value: '#E67700' },
  { label: 'orange-0', value: '#FFF4E6' },
  { label: 'orange-1', value: '#FFE8CC' },
  { label: 'orange-2', value: '#FFD8A8' },
  { label: 'orange-3', value: '#FFC078' },
  { label: 'orange-4', value: '#FFA94D' },
  { label: 'orange-5', value: '#FF922B' },
  { label: 'orange-6', value: '#FD7E14' },
  { label: 'orange-7', value: '#F76707' },
  { label: 'orange-8', value: '#E8590C' },
  { label: 'orange-9', value: '#D9480F' },
]

export const colorOptions: Option[] = [
  { label: 'Mantine', value: 'MantineCategory', category: true },
  ...mantineOptions
]