'use client';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from '@/components/ui/button';
import { Tooltip, TooltipContent, TooltipTrigger, TooltipProvider } from '@/components/ui/tooltip';
import Link from 'next/link';
import { Toaster } from '@/components/ui/toaster';
import { Playground } from '@/components/Playground';
import { InputDialog } from '@/components/InputDialog';
import { Component1Icon } from '@radix-ui/react-icons';
import IndicatorButton from '@/components/IndicatorButton';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <div className="grid h-screen w-full pl-[53px]">
            <aside className="inset-y fixed  left-0 z-20 flex h-full flex-col border-r">
              <div className="border-b p-2">
                <IndicatorButton />
              </div>
              <nav className="grid gap-1 p-2">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="rounded-lg bg-muted"
                      aria-label="Playground"
                    >
                      1
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="right" sideOffset={5}>
                    1
                  </TooltipContent>
                </Tooltip>
              </nav>
            </aside>
            <div className="flex flex-col h-full overflow-hidden">
              {children}
            </div>
          </div>
        </TooltipProvider>
        <Playground />
        <InputDialog />
        <Toaster />
      </body>
    </html>
  );
}
